version: '3.8'

services:
  catwrt:
    image: miaoer/catwrt:latest
    container_name: CatWrt
    restart: always
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - /dev:/dev
    command: /sbin/init

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    networks:
      - maclan

networks:
  maclan:
    external: true
